[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 921600
monitor_speed = 115200

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D CRSF_BAUDRATE=400000
    -D DEBUG_BAUTRATE=${this.monitor_speed}

lib_deps =
    esphome/AsyncTCP-esphome @ ^2.1.3
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2